services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Moscow
      - PLEX_CLAIM=#токен
      - ADVERTISE_IP=http://0.0.0.0:32400/
    hostname: plexD
    volumes:
      - ./db:/config
      - ./transcode:/transcode
      - ./data:/data
